// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDddoEwffsNZl_UYEO4KCqsqCYYrvvnvD8',
    appId: '1:724275837877:web:62d7be83120889ca24b7fc',
    messagingSenderId: '724275837877',
    projectId: 'scheduling-assistant-csc450',
    authDomain: 'scheduling-assistant-csc450.firebaseapp.com',
    storageBucket: 'scheduling-assistant-csc450.firebasestorage.app',
    measurementId: 'G-7N64DVBLTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBee9XYik8RAlwzeq9ictelHrJ7QK22Dgc',
    appId: '1:724275837877:android:160261d3edd8ec6624b7fc',
    messagingSenderId: '724275837877',
    projectId: 'scheduling-assistant-csc450',
    storageBucket: 'scheduling-assistant-csc450.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApb-Q-o8GRjoBntLYF1paU2sv8OJ9iY5Y',
    appId: '1:724275837877:ios:4b22b894cb56a9c424b7fc',
    messagingSenderId: '724275837877',
    projectId: 'scheduling-assistant-csc450',
    storageBucket: 'scheduling-assistant-csc450.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );
}
