name: final_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  intl: ^0.18.0 # Or the latest version


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Or the latest version
  

flutter:
  uses-material-design: true
